# Generated by Django 5.1.7 on 2025-04-12 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_customuser_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='course name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('preferred_start_date', models.DateField(verbose_name='preferred start date')),
                ('preferred_start_time', models.TimeField(verbose_name='preferred start time')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='duration in minutes')),
                ('frequency', models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='once', max_length=20, verbose_name='frequency')),
                ('number_of_sessions', models.IntegerField(default=1, verbose_name='number of sessions')),
                ('teaching_place', models.CharField(max_length=255, verbose_name='teaching place')),
                ('is_online', models.BooleanField(default=False, verbose_name='is online')),
                ('teaching_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='teaching fee')),
                ('is_hourly_rate', models.BooleanField(default=True, verbose_name='is hourly rate')),
                ('teacher_requirements', models.TextField(blank=True, verbose_name='teacher requirements')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('teacher-chosen', 'Teacher Chosen'), ('teacher-responded', 'Teacher Responded'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('is_direct_request', models.BooleanField(default=False, verbose_name='is direct request')),
                ('chosen_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_posts', to='users.teacherprofile', verbose_name='chosen teacher')),
                ('courses', models.ManyToManyField(related_name='posts', to='posts.course', verbose_name='teaching courses')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='learner')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_learner', models.BooleanField(default=True, verbose_name='from learner')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='posts.post')),
            ],
            options={
                'verbose_name': 'post feedback',
                'verbose_name_plural': 'post feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('proposed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='proposed fee')),
                ('is_selected', models.BooleanField(default=False, verbose_name='is selected')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='posts.post')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_applications', to='users.teacherprofile')),
            ],
            options={
                'verbose_name': 'teacher application',
                'verbose_name_plural': 'teacher applications',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'teacher')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='applying_teachers',
            field=models.ManyToManyField(related_name='applied_posts', through='posts.TeacherApplication', to='users.teacherprofile', verbose_name='applying teachers'),
        ),
    ]
